site_name: Writing
site_url: https://finderlzy.github.io/Writing/

theme:
  name: material
  language: zh
  font: false
  features:
    - navigation.path
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
