site_name: Writing

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top

plugins:
  - search
  - pub-obsidian

markdown_extensions:
  - pymdownx.mark