site_name: Writing
site_url: https://finderlzy.github.io/Writing/

theme:
  name: material
  language: zh
  font: false
  favicon: 09附件/writing-logo.png
  features:
    - navigation.path
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - nl2br
